### ISSUE TITLE
请问如何解密网易gis动画文件？

### ISSUE THREAD

**Issue by Pokemon-Rayquaza** [ZhangFengze/NeoXResearch#2]

**Comment by Pokemon-Rayquaza** [comment]
[001_res-000236-01AE90A8-000021BF.txt](https://github.com/ZhangFengze/NeoXResearch/files/11217450/001_res-000236-01AE90A8-000021BF.txt)
![{FDFE4513-6DFF-48E1-8850-319B8DAE5B11} png](https://user-images.githubusercontent.com/88582265/231626796-c7047fa4-6752-43f2-9b8e-0d964000b187.jpg)

**Comment by zhouhang95** [comment]
我搞定了 在我的neox_tools里

**Comment by ZhangFengze** [comment]
> 我搞定了 在我的neox_tools里

cool，当时搜资料还看到你的仓库了，感谢分享
