### ISSUE TITLE
关于新增opcode的分析

### ISSUE THREAD

**Issue by gkdiorflpgh04** [ZhangFengze/NeoXResearch#4]
首先感谢大佬分享，我想请教一下，对于新增的opcode，是怎么看出来是哪几个opcode的组合的呢？
这部分大佬可以不可以细讲一下，目前我找到了那个巨大的switch{}，F5之后代码很乱，实在没看出新增opcode如何看得出来是哪些组合的。希望大佬赐教。

**Comment by ZhangFengze** [comment]
先处理完所有的非新增opcode对应关系和实现

然后看新opcode，大多都很明显，比如先pop，再jump，大概率就是POP_TOP 和 JUMP_FORWARD的组合
把猜的组成成分的实现代码拼起来 看看是不是和目标代码一致
大部分直接就猜对了，少部分可能差些pop、store等小操作

主要是体力活

比较麻烦的是
        新增opcode可能不止由两个旧opcode组成
        有些操作会互相抵消一部分
        还原文件时，因为新opcode要还原成多个opcode，需要改相对地址

如果做讲究了，自动化枚举所有组合 并 对比目标代码效果也行，不过我纯人肉做了一段就翻完了，没搞这花哨的了

**Comment by gkdiorflpgh04** [comment]
@ZhangFengze 
感谢大佬指点，总算是找到点方向了。
我这几天总结了一下，有几个问题还想继续请教一下。

1.最新版的libclient.so加了壳，不过内存dumo修复一下就可以了问题不大。

2.即使我根据反编译代码猜测，猜测出这个opcode是LOAD_CONST+POP_TOP组合，我该怎么去验证这个猜想是否正确？
"把猜的组成成分的实现代码拼起来 看看是不是和目标代码一致"，这个大佬能不能详细讲一下？可以百分百验证完全一致吗？还是只能大概猜测？

3.大佬您代码里研究的libclient.so是哪个版本的？可以上传一下吗，我想对照参悟一下您的opcode分析流程。

说到底还是我功力不太够，面对PyEval_EvalFrameEx里面的反汇编代码，很多case都猜不出来是哪些组合，猜出来也无从验证/(ㄒoㄒ)/~~

**Comment by ZhangFengze** [comment]
> @ZhangFengze 感谢大佬指点，总算是找到点方向了。 我这几天总结了一下，有几个问题还想继续请教一下。
> 
> 1.最新版的libclient.so加了壳，不过内存dumo修复一下就可以了问题不大。
> 
> 2.即使我根据反编译代码猜测，猜测出这个opcode是LOAD_CONST+POP_TOP组合，我该怎么去验证这个猜想是否正确？ "把猜的组成成分的实现代码拼起来 看看是不是和目标代码一致"，这个大佬能不能详细讲一下？可以百分百验证完全一致吗？还是只能大概猜测？
> 
> 3.大佬您代码里研究的libclient.so是哪个版本的？可以上传一下吗，我想对照参悟一下您的opcode分析流程。
> 
> 说到底还是我功力不太够，面对PyEval_EvalFrameEx里面的反汇编代码，很多case都猜不出来是哪些组合，猜出来也无从验证/(ㄒoㄒ)/~~

1. 加壳脱壳我不太了解哈哈
2. 反编译的时候正常会卡壳，修复opcode以后卡壳的地方会过去，卡在别的地方。一个文件的牵扯到的未知opcode全部修复后，反编译是顺畅的，结果是可读的。我是这么简单判断的，不是100%准确，但是好使。
3. 太久了，不可考了
